version: '3'
services:
  app:
    build: .
    working_dir: /cv
    command: hugo server -v --bind "0.0.0.0" --port 1313 --watch -t hugo-theme-cv
    ports:
      - "1313:1313"
    volumes:
      - ./exampleSite:/cv
      - .:/cv/themes/hugo-theme-cv
